src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CartRepository::class)
 */
class Cart
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Mobile::class, inversedBy="carts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProduct(): ?Mobile
    {
        return $this->product;
    }

    public function setProduct(?Mobile $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Entity/Mobile.php
<?php

namespace App\Entity;

use App\Repository\MobileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MobileRepository::class)
 */
class Mobile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $info;

    /**
     * @ORM\ManyToOne(targetEntity=Brand::class, inversedBy="mobiles")
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Amount;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reviews;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rate;

    /**
     * @ORM\ManyToOne(targetEntity=MobileFrom::class, inversedBy="mobiles")
     */
    private $MobileFrom;

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="product")
     */
    private $carts;

    public function __construct()
    {
        $this->carts = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(?int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(?int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function getReviews(): ?int
    {
        return $this->reviews;
    }

    public function setReviews(?int $reviews): self
    {
        $this->reviews = $reviews;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(?int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getMobileFrom(): ?MobileFrom
    {
        return $this->MobileFrom;
    }

    public function setMobileFrom(?MobileFrom $MobileFrom): self
    {
        $this->MobileFrom = $MobileFrom;

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->setProduct($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self
    {
        if ($this->carts->removeElement($cart)) {
            // set the owning side to null (unless already changed)
            if ($cart->getProduct() === $this) {
                $cart->setProduct(null);
            }
        }

        return $this;
    }

    
    
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Cart;
use App\Entity\Mobile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity',IntegerType::class,
            [
                'label'=> 'Quantity',
            ])
            ->add('product',EntityType::class,
            [
                'label'=> 'Product',
                'class' => Mobile::class,
                'choice_label' => "name",
                'multiple' => false,
                'expanded' => false 
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cart::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\Mobile;
use App\Form\CartType;
use App\Form\MobileType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(): Response
    {
        $cart = $this->getDoctrine()->getRepository(Cart::class)->findAll();
        return $this->render(
            'cart/index.html.twig',
            [
                'cart' => $cart
            ]
        );  
    }

    /**
     * @Route("/cart/add", name="cart_add")
     */

    public function cartAdd(Request $request) {
        
        $cart = new Cart();
        $form = $this->createForm(CartType::class,$cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($cart);
            $manager->flush();

            $this->addFlash("Success", "Add product to cart successfully !");
            return $this->redirectToRoute('cart');
        }

        return $this->render(
            "cart/add.html.twig", 
            [
                "form" => $form->createView()
            ]
        );
    }

    /**
     * @Route("/cart/delete{id}", name="cart_delete")
     */
    public function cartDelete($id) {
        $cart = $this->getDoctrine()->getRepository(Cart::class)->find($id);
         
            $manager = $this->getDoctrine()->getManager();
            $manager->remove($cart);
            $manager->flush();
            $this->addFlash('Success', 'Delete magazine successfully !');
        
        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/edit/{id}", name="cart_edit")
     */
    public function cartEdit(Request $request, $id) {
        $cart = $this->getDoctrine()->getRepository(Cart::class)->find($id);
        $form = $this->createForm(CartType::class,$cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($cart);
            $manager->flush();

            $this->addFlash("Success", "Add new magazine successfully !");
            return $this->redirectToRoute('cart');
        }

        return $this->render(
            "cart/edit.html.twig", 
            [
                "form" => $form->createView()
            ]
        );
    
    }
}

templates/cart/add.html.twig
{% extends "base.html.twig" %}
{% block title %}Order
{% endblock %}
{% block body %}

<div class="container">
   <h2 class="text-center mt-2">ADD PRODUCT TO CART</h2>
      {{ form_start (form) }}
         <div class="form-group mx-5">
            {{ form_label (form.product) }}
            {{ form_widget (form.product,
               {
                  'attr' : {'class' : 'form-control'}
               })
            }}
         </div>
         <div class="form-group mx-5">
            {{ form_label (form.quantity) }}
            {{ form_widget (form.quantity,
               {
                  'attr' : {'class' : 'form-control','placeholder':'Enter the quantity you want to order'}
               })
            }}
         </div>
       
         <div class="form-group text-center mt-3">
            <button class="btn btn-primary" type="submit">ADD</button>
         </div>
      {{ form_end (form) }}
   </div>
</div>
{% endblock %}

templates/cart/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container">
   <h2 class="text-center mt-2">UPDATE PRODUCT TO CART</h2>
   <div class="col-md-6"></div>
      {{ form_start (form) }}
         <div class="form-group">
            {{ form_label (form.product) }}
            {{ form_widget (form.product,
               {
                  'attr' : {'class' : 'form-control'}
               })
            }}
         </div>
         <div class="form-group">
            {{ form_label (form.quantity) }}
            {{ form_widget (form.quantity,
               {
                  'attr' : {'class' : 'form-control'}
               })
            }}
         </div>
       
         <div class="form-group text-center mt-3">
            <button class="btn btn-primary" type="submit">UPDATE</button>
         </div>
      {{ form_end (form) }}
   </div>
</div>
{% endblock %}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart Homepapge
{% endblock %}

{% block body %}
	
<div class="container">

	<table class="table">
		<thead>
			<tr>
				<th scope="col">Image</th>
				<th scope="col">Name product</th>
				<th scope="col">Quantity</th>
				<th scope="col">Unit Price</th>
				<th scope="col">Total</th>
				<th scope="col"></th>
				
			</tr>
		</thead>
		<tbody>
            {% for cart in cart %}
            <tr>
				<td><img src="{{asset ('uploads/images/'~ cart.product.image)}}" height="200px"></td>
				<td>{{cart.product.name}}</td>
				<td>{{cart.quantity}}</td>
				<td>${{cart.product.price}}</td>
				<td>${{cart.product.price * cart.quantity}}</td>
				<td><a href="{{path ('cart_edit',{'id':cart.id})}}"><i class="bi bi-pencil"></i></a></td>
				<td><a href="{{path ('cart_delete',{'id':cart.id})}}" ><i class="bi bi-trash"></i></a></td>
			</tr>
            {% endfor %}
			

		</tbody>
	</table>

	{% set var = 0 %}
	{% for cart in cart %}
		{% set total = cart.product.price * cart.quantity %}
		{% set var = total + var %}
	{% endfor %}

	Total of cart : $ {{var}}
	<br>
	
	
	<a href="{{path('cart_add')}}"><button type="button" class="btn btn-primary">Add to cart</button></a>

	</div>
{% endblock %}